In [1]:
import sys
sys.path.append("src")
from loan_default_ml_pipeline.ingestion.load_data import load_raw_data
from loan_default_ml_pipeline.validation.data_quality import null_summary

df = load_raw_data()
null_summary(df)

                                  missing_count  percent_missing    dtype
verification_income_joint                  8545            85.45   object
debt_to_income_joint                       8505            85.05  float64
annual_income_joint                        8505            85.05  float64
months_since_90d_late                      7715            77.15  float64
months_since_last_delinq                   5658            56.58  float64
months_since_last_credit_inquiry           1271            12.71  float64
emp_title                                   833             8.33   object
emp_length                                  817             8.17  float64
num_accounts_120d_past_due                  318             3.18  float64
debt_to_income                               24             0.24  float64
installment                                   0             0.00  float64
num_mort_accounts                             0             0.00    int64
account_never_delinq_percent                  0             0.00  float64
tax_liens                                     0             0.00    int64
public_record_bankrupt                        0             0.00    int64
loan_purpose                                  0             0.00   object
application_type                              0             0.00   object
loan_amount                                   0             0.00    int64
term                                          0             0.00    int64
interest_rate                                 0             0.00  float64
grade                                         0             0.00   object
delinq_2y                                     0             0.00    int64
sub_grade                                     0             0.00   object
issue_month                                   0             0.00   object
loan_status                                   0             0.00   object
initial_listing_status                        0             0.00   object
disbursement_method                           0             0.00   object
balance                                       0             0.00  float64
paid_total                                    0             0.00  float64
paid_principal                                0             0.00  float64
paid_interest                                 0             0.00  float64
num_cc_carrying_balance                       0             0.00    int64
num_open_cc_accounts                          0             0.00    int64
num_total_cc_accounts                         0             0.00    int64
total_debit_limit                             0             0.00    int64
verified_income                               0             0.00   object
earliest_credit_line                          0             0.00    int64
inquiries_last_12m                            0             0.00    int64
total_credit_lines                            0             0.00    int64
open_credit_lines                             0             0.00    int64
total_credit_limit                            0             0.00    int64
total_credit_utilized                         0             0.00    int64
num_collections_last_12m                      0             0.00    int64
num_historical_failed_to_pay                  0             0.00    int64
annual_income                                 0             0.00  float64
current_accounts_delinq                       0             0.00    int64
total_collection_amount_ever                  0             0.00    int64
current_installment_accounts                  0             0.00    int64
accounts_opened_24m                           0             0.00    int64
homeownership                                 0             0.00   object
num_satisfactory_accounts                     0             0.00    int64
state                                         0             0.00   object
num_accounts_30d_past_due                     0             0.00    int64
num_active_debit_accounts                     0             0.00    int64
paid_late_fees                                0             0.00  float64

In [ ]:
# Check if the large null counts from *_joint columns coincide with application_type = 'joint'
import pandas as pd
results = []

for col in [c for c in df.columns if c.endswith('_joint')]:
    results.append({
        "column": col,
        "missing_when_joint": df[(df[col].isnull()) & \
                                 (df['application_type'] == 'joint')].shape[0],
        "present_when_individual": df[(df[col].notnull()) & \
                                      (df['application_type'] == 'individual')].shape[0]
    })

pd.DataFrame(results)

                      column  missing_when_joint  present_when_individual
0        annual_income_joint                   0                        0
1  verification_income_joint                  40                        0
2       debt_to_income_joint                   0                        0

In [8]:
df.describe()

,emp_length,annual_income,debt_to_income,annual_income_joint,debt_to_income_joint,delinq_2y,months_since_last_delinq,earliest_credit_line,inquiries_last_12m,total_credit_lines,...,public_record_bankrupt,loan_amount,term,interest_rate,installment,balance,paid_total,paid_principal,paid_interest,paid_late_fees
count,9183.000000,1.000000e+04,9976.000000,1.495000e+03,1495.000000,10000.00000,4342.000000,10000.00000,10000.00000,10000.000000,...,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000
mean,5.930306,7.922215e+04,19.308192,1.279146e+05,19.979304,0.21600,36.760709,2001.29000,1.95820,22.679600,...,0.123800,16361.922500,43.272000,12.427524,476.205323,14458.916610,2494.234773,1894.448466,599.666781,0.119516
std,3.703734,6.473429e+04,15.004851,7.016838e+04,8.054781,0.68366,21.634939,7.79551,2.38013,11.885439,...,0.337172,10301.956759,11.029877,5.001105,294.851627,9964.561865,3958.230365,3884.407175,517.328062,1.813468
min,0.000000,0.000000e+00,0.000000,1.920000e+04,0.320000,0.00000,1.000000,1963.00000,0.00000,2.000000,...,0.000000,1000.000000,36.000000,5.310000,30.750000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,2.000000,4.500000e+04,11.057500,8.683350e+04,14.160000,0.00000,19.000000,1997.00000,0.00000,14.000000,...,0.000000,8000.000000,36.000000,9.430000,256.040000,6679.065000,928.700000,587.100000,221.757500,0.000000
50%,6.000000,6.500000e+04,17.570000,1.130000e+05,19.720000,0.00000,34.000000,2003.00000,1.00000,21.000000,...,0.000000,14500.000000,36.000000,11.980000,398.420000,12379.495000,1563.300000,984.990000,446.140000,0.000000
75%,10.000000,9.500000e+04,25.002500,1.515455e+05,25.500000,0.00000,53.000000,2006.00000,3.00000,29.000000,...,0.000000,24000.000000,60.000000,15.050000,644.690000,20690.182500,2616.005000,1694.555000,825.420000,0.000000
max,10.000000,2.300000e+06,469.090000,1.100000e+06,39.980000,13.00000,118.000000,2015.00000,29.00000,87.000000,...,3.000000,40000.000000,60.000000,30.940000,1566.590000,40000.000000,41630.443684,40000.000000,4216.440000,52.980000

In [9]:
df.columns.tolist()

['emp_title',
 'emp_length',
 'state',
 'homeownership',
 'annual_income',
 'verified_income',
 'debt_to_income',
 'annual_income_joint',
 'verification_income_joint',
 'debt_to_income_joint',
 'delinq_2y',
 'months_since_last_delinq',
 'earliest_credit_line',
 'inquiries_last_12m',
 'total_credit_lines',
 'open_credit_lines',
 'total_credit_limit',
 'total_credit_utilized',
 'num_collections_last_12m',
 'num_historical_failed_to_pay',
 'months_since_90d_late',
 'current_accounts_delinq',
 'total_collection_amount_ever',
 'current_installment_accounts',
 'accounts_opened_24m',
 'months_since_last_credit_inquiry',
 'num_satisfactory_accounts',
 'num_accounts_120d_past_due',
 'num_accounts_30d_past_due',
 'num_active_debit_accounts',
 'total_debit_limit',
 'num_total_cc_accounts',
 'num_open_cc_accounts',
 'num_cc_carrying_balance',
 'num_mort_accounts',
 'account_never_delinq_percent',
 'tax_liens',
 'public_record_bankrupt',
 'loan_purpose',
 'application_type',
 'loan_amount',
 'term',
 'interest_rate',
 'installment',
 'grade',
 'sub_grade',
 'issue_month',
 'loan_status',
 'initial_listing_status',
 'disbursement_method',
 'balance',
 'paid_total',
 'paid_principal',
 'paid_interest',
 'paid_late_fees']

In [12]:
df['loan_status'].value_counts()

loan_status
Current               9375
Fully Paid             447
In Grace Period         67
Late (31-120 days)      66
Late (16-30 days)       38
Charged Off              7
Name: count, dtype: int64